### ISSUE TITLE
Package update timeout.

### ISSUE THREAD

**Issue by MaxMommersteeg** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#14]
Initially the Azure DevOps extension worked just fine, opening up pull requests. Since a few weeks we get the following error in our build when using the task provided by NuKeeper-AzureDevOps-extension:
```
2019-01-31T17:33:08.7662890Z Wrote report for 35 updates
2019-01-31T17:33:08.7863889Z Resorted 35 packages by dependencies, first change is Microsoft.ServiceFabric moved to position 0 from 2.
2019-01-31T17:33:08.7932405Z Filtered by rules from 35 to 0
2019-01-31T17:33:08.8052714Z Selection of package updates: 35 candidates, filtered to 0
2019-01-31T17:33:08.8090792Z No updates can be applied. Exiting.
2019-01-31T17:33:08.8101503Z Done at 2019-01-31T17:33:08Z
2019-01-31T17:33:08.8381610Z ##[debug]task result: Succeeded
2019-01-31T17:33:08.8384345Z ##[debug]Processed: ##vso[task.complete result=Succeeded;]done
2019-01-31T18:33:00.4928304Z ##[debug]Re-evaluate condition on job cancellation for step: 'NuKeeper package update'.
2019-01-31T18:33:00.5383646Z ##[error]The operation was canceled.
2019-01-31T18:33:00.5430336Z ##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
```

Not sure what caused this to happen. We did not change the build pipeline. The task just gets cancelled automatically by the agent since it has been running for over an hour. Looking at the source it looks like the extension is still using NuKeeper 0.13.0 instead of the latest version. Could there already be a fix for this issue?

**Comment by MarcBruins** [comment]
Just updated to the latest version, can you try again? There was no fix for this specific issue. Not sure what the issue is, NuKeeper seems to exit gracefully(https://github.com/NuKeeperDotNet/NuKeeper/blob/7d750c1f2e24fd746639c387753092f6a1961097/NuKeeper/Engine/RepositoryUpdater.cs#L88). After that i should just quit

**Comment by MaxMommersteeg** [comment]
Thanks, I will run the build today.

**Comment by MaxMommersteeg** [comment]
Update:
I ran the build again and it resulted in the same error:
![issue](https://user-images.githubusercontent.com/9657173/52262453-d035d700-292c-11e9-896e-074cf8b58e8d.png)

**Comment by MarcBruins** [comment]
To bad. Maybe it's something with the post job cleanup.. Will have to investigate further

**Comment by MaxMommersteeg** [comment]
Alright, let me know when you need more information about this issue.

**Comment by MarcBruins** [comment]
Should be fixed now, can you confirm?

**Comment by MaxMommersteeg** [comment]
Will check this today.

**Comment by MaxMommersteeg** [comment]
Now getting a different error:

```
2019-02-14T12:10:15.7615521Z ##[section]Starting: NuKeeper Microsoft Test
2019-02-14T12:10:15.7619227Z ==============================================================================
2019-02-14T12:10:15.7619487Z Task         : NuKeeper
2019-02-14T12:10:15.7619666Z Description  : Version 0.1.62
2019-02-14T12:10:15.7619843Z Version      : 0.1.62
2019-02-14T12:10:15.7620023Z Author       : NuKeeper
2019-02-14T12:10:15.7620247Z Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
2019-02-14T12:10:15.7620504Z ==============================================================================
2019-02-14T12:10:16.0894469Z ##[debug]agent.TempDirectory=C:\agents\agent1\_work\_temp
2019-02-14T12:10:16.0973865Z ##[debug]loading inputs and endpoints
2019-02-14T12:10:16.0981010Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-02-14T12:10:16.0993240Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-02-14T12:10:16.0996598Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-02-14T12:10:16.0999647Z ##[debug]loading INPUT_ARGUMENTS
2019-02-14T12:10:16.1004161Z ##[debug]loaded 4
2019-02-14T12:10:16.1019878Z ##[debug]Agent.ProxyUrl=undefined
2019-02-14T12:10:16.1021780Z ##[debug]Agent.CAInfo=undefined
2019-02-14T12:10:16.1022224Z ##[debug]Agent.ClientCert=undefined
2019-02-14T12:10:16.1022552Z ##[debug]Agent.SkipCertValidation=undefined
2019-02-14T12:10:16.1324778Z ##[debug]Agent.ProxyUrl=undefined
2019-02-14T12:10:16.1329761Z ##[debug]check path : C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.1.62\node_modules\vsts-task-tool-lib\lib.json
2019-02-14T12:10:16.1332256Z ##[debug]adding resource file: C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.1.62\node_modules\vsts-task-tool-lib\lib.json
2019-02-14T12:10:16.1332644Z ##[debug]system.culture=en-US
2019-02-14T12:10:16.1360343Z ##[debug]which 'curl'
2019-02-14T12:10:16.1468200Z ##[debug]not found
2019-02-14T12:10:16.1500468Z ##[debug]task result: Failed
2019-02-14T12:10:16.1587882Z ##[error]Error: Unable to locate executable file: 'curl'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
2019-02-14T12:10:16.1589181Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Unable to locate executable file: 'curl'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
2019-02-14T12:10:16.1591272Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Unable to locate executable file: 'curl'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
2019-02-14T12:10:16.1604847Z ##[section]Finishing: NuKeeper Microsoft Test
```

**Comment by MarcBruins** [comment]
Can you rerun? Version should be 0.1.69

**Comment by MaxMommersteeg** [comment]
New exception:
```
2019-02-14T22:23:07.6017901Z ##[debug]Evaluating condition for step: 'NuKeeper Microsoft Test'
2019-02-14T22:23:07.6018583Z ##[debug]Evaluating: succeeded()
2019-02-14T22:23:07.6018791Z ##[debug]Evaluating succeeded:
2019-02-14T22:23:07.6019177Z ##[debug]=> (Boolean) True
2019-02-14T22:23:07.6019509Z ##[debug]Expanded: True
2019-02-14T22:23:07.6019707Z ##[debug]Result: True
2019-02-14T22:23:07.6019999Z ##[section]Starting: NuKeeper Microsoft Test
2019-02-14T22:23:07.6026545Z ==============================================================================
2019-02-14T22:23:07.6026684Z Task         : NuKeeper
2019-02-14T22:23:07.6026839Z Description  : Version 0.2.1
2019-02-14T22:23:07.6026939Z Version      : 0.2.1
2019-02-14T22:23:07.6027036Z Author       : NuKeeper
2019-02-14T22:23:07.6027189Z Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
2019-02-14T22:23:07.6027313Z ==============================================================================
2019-02-14T22:23:07.8856829Z ##[debug]agent.TempDirectory=C:\agents\agent1\_work\_temp
2019-02-14T22:23:07.8937529Z ##[debug]loading inputs and endpoints
2019-02-14T22:23:07.8944516Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-02-14T22:23:07.8962794Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-02-14T22:23:07.8967734Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-02-14T22:23:07.8970352Z ##[debug]loading INPUT_ARGUMENTS
2019-02-14T22:23:07.8977442Z ##[debug]loaded 4
2019-02-14T22:23:07.8998105Z ##[debug]Agent.ProxyUrl=undefined
2019-02-14T22:23:07.9000271Z ##[debug]Agent.CAInfo=undefined
2019-02-14T22:23:07.9001056Z ##[debug]Agent.ClientCert=undefined
2019-02-14T22:23:07.9001758Z ##[debug]Agent.SkipCertValidation=undefined
2019-02-14T22:23:07.9432635Z ##[debug]Agent.ProxyUrl=undefined
2019-02-14T22:23:07.9434453Z ##[debug]Agent.CAInfo=undefined
2019-02-14T22:23:07.9435178Z ##[debug]Agent.ClientCert=undefined
2019-02-14T22:23:07.9440745Z ##[debug]check path : C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\node_modules\azure-pipelines-tool-lib\lib.json
2019-02-14T22:23:07.9444339Z ##[debug]adding resource file: C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\node_modules\azure-pipelines-tool-lib\lib.json
2019-02-14T22:23:07.9445409Z ##[debug]system.culture=en-US
2019-02-14T22:23:07.9496124Z ##[debug]nukeeper.nupkg
2019-02-14T22:23:07.9500173Z ##[debug]Agent.Version=2.127.0
2019-02-14T22:23:07.9500534Z ##[debug]Agent.TempDirectory=C:\agents\agent1\_work\_temp
2019-02-14T22:23:07.9514417Z ##[debug]testing directory 'C:\agents\agent1\_work\_temp'
2019-02-14T22:23:07.9562588Z Downloading: https://www.nuget.org/api/v2/package/NuKeeper
2019-02-14T22:23:07.9563129Z ##[debug]destination C:\agents\agent1\_work\_temp\nukeeper.nupkg
2019-02-14T22:23:07.9565439Z ##[debug]downloading
2019-02-14T22:23:08.9562960Z ##[debug]creating stream
2019-02-14T22:23:09.2891561Z ##[debug]download complete
2019-02-14T22:23:09.2896577Z Extracting archive
2019-02-14T22:23:09.2898038Z ##[debug]testing directory 'C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\src\nukeeper'
2019-02-14T22:23:09.2906354Z ##[debug]which 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.2915007Z ##[debug]found: 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.2915320Z ##[debug]which 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.2916711Z ##[debug]found: 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.2919095Z ##[debug]C:\Windows\system32\chcp.com arg: 65001
2019-02-14T22:23:09.2919519Z ##[debug]C:\Windows\system32\chcp.com arg: 65001
2019-02-14T22:23:09.2928796Z ##[debug]exec tool: C:\Windows\system32\chcp.com
2019-02-14T22:23:09.2929128Z ##[debug]exec tool: C:\Windows\system32\chcp.com
2019-02-14T22:23:09.2929450Z ##[debug]arguments:
2019-02-14T22:23:09.2929720Z ##[debug]arguments:
2019-02-14T22:23:09.2930016Z ##[debug]   65001
2019-02-14T22:23:09.2930233Z ##[debug]   65001
2019-02-14T22:23:09.2940218Z [command]C:\Windows\system32\chcp.com 65001
2019-02-14T22:23:09.3179754Z Active code page: 65001
2019-02-14T22:23:09.3198096Z ##[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.3198399Z ##[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.3206885Z ##[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.3207138Z ##[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
2019-02-14T22:23:09.3223587Z ##[debug]which 'powershell'
2019-02-14T22:23:09.3275347Z ##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2019-02-14T22:23:09.3275604Z ##[debug]which 'powershell'
2019-02-14T22:23:09.3329205Z ##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2019-02-14T22:23:09.3330237Z ##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command
2019-02-14T22:23:09.3332996Z ##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\agents\agent1\_work\_temp\nukeeper.nupkg', 'C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\src\nukeeper')
2019-02-14T22:23:09.3334152Z ##[debug]exec tool: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
2019-02-14T22:23:09.3334749Z ##[debug]arguments:
2019-02-14T22:23:09.3335014Z ##[debug]   -NoLogo
2019-02-14T22:23:09.3335319Z ##[debug]   -Sta
2019-02-14T22:23:09.3335576Z ##[debug]   -NoProfile
2019-02-14T22:23:09.3336102Z ##[debug]   -NonInteractive
2019-02-14T22:23:09.3336498Z ##[debug]   -ExecutionPolicy
2019-02-14T22:23:09.3336806Z ##[debug]   Unrestricted
2019-02-14T22:23:09.3337075Z ##[debug]   -Command
2019-02-14T22:23:09.3337339Z ##[debug]   $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\agents\agent1\_work\_temp\nukeeper.nupkg', 'C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\src\nukeeper')
2019-02-14T22:23:09.3342732Z [command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\agents\agent1\_work\_temp\nukeeper.nupkg', 'C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\src\nukeeper')"
2019-02-14T22:23:09.9589980Z Exception calling "ExtractToDirectory" with "2" argument(s): "The file 
2019-02-14T22:23:09.9593002Z 'C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.2.1\src\nukeeper\_rels\.rels' already 
2019-02-14T22:23:09.9593537Z exists."
2019-02-14T22:23:09.9594115Z At line:1 char:111
2019-02-14T22:23:09.9594974Z + ... catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\a ...
2019-02-14T22:23:09.9595267Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-02-14T22:23:09.9595909Z     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
2019-02-14T22:23:09.9596128Z     + FullyQualifiedErrorId : IOException
2019-02-14T22:23:09.9596392Z  
2019-02-14T22:23:09.9906991Z ##[debug]Exit code 1 received from tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2019-02-14T22:23:09.9909233Z ##[debug]STDIO streams have closed for tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
2019-02-14T22:23:09.9929016Z ##[debug]task result: Failed
2019-02-14T22:23:10.0028288Z ##[error]Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
2019-02-14T22:23:10.0028517Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
2019-02-14T22:23:10.0030173Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
2019-02-14T22:23:10.0031859Z ##[section]Finishing: NuKeeper Microsoft Test
```

Noticed that version 0.2.2 is out, but i'm not sure how I can force the build to use that latest version.

**Comment by MarcBruins** [comment]
Can you retry now?

**Comment by MaxMommersteeg** [comment]
I tried, it is stuck on the timeout again:

```
##[debug]Evaluating condition for step: 'NuKeeper Microsoft Test'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> (Boolean) True
##[debug]Expanded: True
##[debug]Result: True
##[section]Starting: NuKeeper Microsoft Test
==============================================================================
Task         : NuKeeper
Description  : Version 0.3.4
Version      : 0.3.4
Author       : NuKeeper
Help         : For help please visit https://github.com/NuKeeperDotNet/NuKeeper
==============================================================================
##[debug]agent.TempDirectory=C:\agents\agent1\_work\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_ARGUMENTS
##[debug]loaded 4
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.3.4\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]adding resource file: C:\agents\agent1\_work\_tasks\NuKeeper_e5a17a66-903f-46a9-a9b9-94241bcedc39\0.3.4\node_modules\azure-pipelines-tool-lib\lib.json
##[debug]system.culture=en-US
##[debug]Agent.TempDirectory=C:\agents\agent1\_work\_temp
##[debug]nukeeper.nupkg
##[debug]Agent.Version=2.127.0
##[debug]Agent.TempDirectory=C:\agents\agent1\_work\_temp
##[debug]testing directory 'C:\agents\agent1\_work\_temp'
Downloading: https://www.nuget.org/api/v2/package/NuKeeper
##[debug]destination C:\agents\agent1\_work\_temp\nukeeper.nupkg
##[debug]downloading
##[debug]creating stream
##[debug]download complete
Extracting archive
##[debug]testing directory 'C:\agents\agent1\_work\_temp\nukeeper'
##[debug]testing directory 'C:\agents\agent1\_work\_temp'
##[debug]mkdir 'C:\agents\agent1\_work\_temp\nukeeper'
##[debug]which 'C:\Windows\system32\chcp.com'
##[debug]found: 'C:\Windows\system32\chcp.com'
##[debug]which 'C:\Windows\system32\chcp.com'
##[debug]found: 'C:\Windows\system32\chcp.com'
##[debug]C:\Windows\system32\chcp.com arg: 65001
##[debug]C:\Windows\system32\chcp.com arg: 65001
##[debug]exec tool: C:\Windows\system32\chcp.com
##[debug]exec tool: C:\Windows\system32\chcp.com
##[debug]arguments:
##[debug]arguments:
##[debug]   65001
##[debug]   65001
[command]C:\Windows\system32\chcp.com 65001
Active code page: 65001
##[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
##[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
##[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
##[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
##[debug]which 'powershell'
##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]which 'powershell'
##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command
##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\agents\agent1\_work\_temp\nukeeper.nupkg', 'C:\agents\agent1\_work\_temp\nukeeper')
##[debug]exec tool: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -Sta
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\agents\agent1\_work\_temp\nukeeper.nupkg', 'C:\agents\agent1\_work\_temp\nukeeper')
[command]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('C:\agents\agent1\_work\_temp\nukeeper.nupkg', 'C:\agents\agent1\_work\_temp\nukeeper')"
##[debug]Exit code 0 received from tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]STDIO streams have closed for tool 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]which 'git'
##[debug]found: 'C:\agents\agent1\externals\git\cmd\git.exe'
##[debug]which 'git'
##[debug]found: 'C:\agents\agent1\externals\git\cmd\git.exe'
##[debug]C:\agents\agent1\externals\git\cmd\git.exe arg: fetch
##[debug]C:\agents\agent1\externals\git\cmd\git.exe arg: fetch
##[debug]exec tool: C:\agents\agent1\externals\git\cmd\git.exe
##[debug]exec tool: C:\agents\agent1\externals\git\cmd\git.exe
##[debug]arguments:
##[debug]arguments:
##[debug]   fetch
##[debug]   fetch
[command]C:\agents\agent1\externals\git\cmd\git.exe fetch
##[debug]Re-evaluate condition on job cancellation for step: 'NuKeeper Microsoft Test'.
##[error]The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.<RunAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
##[section]Finishing: NuKeeper Microsoft Test
```

**Comment by MarcBruins** [comment]
Did you add your oauth token as trusted? Like suggested in the readme.md?

**Comment by MaxMommersteeg** [comment]
Check, I didn't notice that change. It seems to work now, thanks!
