### ISSUE TITLE
Cannot checkout when using NuKeeper extension on a branch with slash

### ISSUE THREAD

**Issue by thomasmktong** [NuKeeperDotNet/NuKeeper-AzureDevops-extension#37]
When running NuKeeper extension on a branch with slash, e.g. `bug/31386-xxx` I found that only the last segment of the branch is sent to NuKeeper, i.e. `31386-xxx` without `bug/`

```
##[debug]Build.SourceBranchName=31386-xxx
##[debug]arguments=--maxpackageupdates 1000 --change minor --consolidate --verbosity detailed --exclude MathNet
:\Program Files\dotnet\dotnet.exe" C:\vsts_agent_integration\_work\_tool\nukeeper\0.21.3\x64\NuKeeper.dll repo C:\vsts_agent_integration\_work\35\s *** --targetBranch origin/31386-xxx --maxpackageupdates 1000 --change minor --consolidate --verbosity detailed
```
```
Git checkout 'origin/31386-xxx'
Updates failed NuKeeperException : Git Cannot checkout branch: the branch named 'origin/31386-xxx' doesn't exist
   at NuKeeper.Git.LibGit2SharpDriver.Checkout(String branchName) in /home/vsts/work/r1/a/drop/NuKeeper.Git/LibGit2SharpDriver.cs:line 96
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, NuGetSources sources, SettingsContainer settings, IReadOnlyCollection`1 updates) in /home/vsts/work/r1/a/drop/NuKeeper/Engine/Packages/PackageUpdater.cs:line 70
   at NuKeeper.Engine.Packages.PackageUpdater.MakeUpdatePullRequests(IGitDriver git, RepositoryData repository, IReadOnlyCollection`1 updates, NuGetSources sources, SettingsContainer settings) in /home/vsts/work/r1/a/drop/NuKeeper/Engine/Packages/PackageUpdater.cs:line 46
Attempted 134 updates and did 0
Done at 2019-06-01T04:15:58Z
```

I think somehow the VSTS build variable `Build.SourceBranchName` was used as that one only has last segment of a branch name, ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by MaxMommersteeg** [comment]
I think you are right: https://github.com/NuKeeperDotNet/NuKeeper-AzureDevops-extension/blob/master/nukeeper/src/NuKeeper.ts#L18

Could you give me the exact arguments you are using? I can try to replicate and fix the issue later today.

**Comment by thomasmktong** [comment]
Thanks. I just run the task with these
```
--maxpackageupdates 1000 --change minor --consolidate --verbosity detailed
```
![image](https://user-images.githubusercontent.com/7279232/58759768-f88fb400-8561-11e9-8996-e30fa7d00ce6.png)
it this what you are looking for?

**Comment by MaxMommersteeg** [comment]
Yep, thanks. Is bug/31386-xxx the default branch, or do you target that one in the pipeline?

**Comment by MaxMommersteeg** [comment]
I opened up a PR, I think that code change will fix the issue you're experiencing.

**Comment by thomasmktong** [comment]
thanks very much, it was the branch that i targeted

**Comment by MaxMommersteeg** [comment]
@thomasmktong Could you try again, new version of extension should be live.
